### ISSUE TITLE
Record "iconfile" broken with IconRegistry::registerIcon() in ext_localconf.php

### ISSUE THREAD

**Issue by mbrodala** [netresearch/t3x-contexts#14]
The [following line](https://github.com/netresearch/t3x-contexts/blob/f320112ea633bb9b13eea9f1e07e6525cb7a13ca/ext_localconf.php#L44-L45) breaks registration of all record icons via [`iconfile`](https://docs.typo3.org/typo3cms/TCAReference/Ctrl/Index.html#iconfile) if at least one extension uses `IconRegistry::registerIcon()` in `ext_localconf.php` as suggested by the official docs ([fix merged](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/165)):

```php
$GLOBALS['TCA']['tx_contexts_contexts']
    = include \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('contexts', 'Configuration/TCA/tx_contexts_contexts.php');
```

This is because `IconRegistry::__construct()` calls its `initialize()` method which among others registers icons for all TCA tables, based on `iconfile`. Normally this would not be an issue since `$GLOBALS['TCA']` does not exist in `ext_localconf.php`, thus the `IconRegistry` would postpone the full initialization to a later point. However, with the line above `$GLOBALS['TCA']['tx_contexts_contexts']` unexpectedly exists, causing the `IconRegistry` to process this single table and marking itself as fully initialized.

This results in all tables except `tx_contexts_contexts` using `iconfile` showing the default/broken icon instead of their `iconfile`. For example the formhandler extension [registers its icon in `ext_localconf.php`](https://github.com/reinhardfuehricht/typo3-formhandler/blob/fabf64a7e39719800c7eb70ed6ea3ab422446c84/ext_localconf.php#L26-L33) and thus triggers this behavior.

What does this line exactly and can it be moved to `ext_tables.php` instead?

**Comment by copitz** [comment]
Hi Mathias,

not sure why the line was still there - I guess it was kind of a relict. Please check with current master if it works.

Cheers,
Christian

**Comment by mbrodala** [comment]
Yes, this fixes the issue, thanks.
