### ISSUE TITLE
Invalid IP address

### ISSUE THREAD

**Issue by woodyc79** [netresearch/t3x-contexts#25]
Hello!

Unfortunately on some Pages in TYPO3 it just get an error:
Invalid IP address: '2a03:2a00:1400:2::ac15:901a'

On other pages it does work... what could be the problem?

Kind regards,
Christian Holzmann

**Comment by magicsunday** [comment]
Closed. If the error still occurs, please reopen the ticket with a detailed description of the error to reproduce it.
