### ISSUE TITLE
packagist.org: The netresearch/contexts package of which you are a maintainer has failed to update due to invalid data contained in your composer.json.

### ISSUE THREAD

**Issue by CybotTM** [netresearch/t3x-contexts#26]
The netresearch/contexts package of which you are a maintainer has failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use `composer validate` to check for errors when you change your composer.json.

Below is the full update log which should highlight errors as "Skipped branch ...":

[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

Reading composer.json of netresearch/contexts (v1.0.0)
Found cached composer.json of netresearch/contexts (v1.0.0)
Reading composer.json of netresearch/contexts (v0.5.2)
Skipped v0.5.2, no composer file (cached from ref 3fed9b7e135ccb7b2485fcc6cea8b0148bb6587e)
Reading composer.json of netresearch/contexts (v0.5.1)
Skipped v0.5.1, no composer file (cached from ref c56106b72abdbc52791c2cb205a6ef956e8217a5)
Reading composer.json of netresearch/contexts (v0.5.0)
Skipped v0.5.0, no composer file (cached from ref add83a1cfe69fd9d905d887a505c7827ae1fb467)
Reading composer.json of netresearch/contexts (v0.4.3)
Skipped v0.4.3, no composer file (cached from ref b6a77b4261272ff3ab90885d30787aa0599cc782)
Reading composer.json of netresearch/contexts (v0.4.2)
Skipped v0.4.2, no composer file (cached from ref 696962c05c1a2c0504804e0d01563fb6f7bae44b)
Reading composer.json of netresearch/contexts (v0.4.1)
Skipped v0.4.1, no composer file (cached from ref 9cb821e08dd41f3a89646c8a380b4ce18679dc7a)
Reading composer.json of netresearch/contexts (v0.4.0)
Skipped v0.4.0, no composer file (cached from ref a3f69202f8c55097faa33b07e052c334e4faf08a)
Reading composer.json of netresearch/contexts (v0.3.1)
Skipped v0.3.1, no composer file (cached from ref 4465071b1cce9df066a5480cc9470daff5f7978e)
Reading composer.json of netresearch/contexts (v0.3.0)
Skipped v0.3.0, no composer file (cached from ref 69092788db6138024783f891099774c284176f0e)
Reading composer.json of netresearch/contexts (v0.2.1)
Skipped v0.2.1, no composer file (cached from ref bbcc83018e9902ccc4c767414fb92ee7f74b8a14)
Reading composer.json of netresearch/contexts (v0.2.0)
Skipped v0.2.0, no composer file (cached from ref 1e32fd1aa3acf6a3ad40de5f6eaf0bc5093c31d5)
Reading composer.json of netresearch/contexts (v0.1.0)
Skipped v0.1.0, no composer file (cached from ref 1a5c23efbb99563241718b82ed96e78ce01c7659)
Reading composer.json of netresearch/contexts (master)
Importing branch master (dev-master)
Skipped branch master, Invalid package information:
Deprecation warning: replace.contexts is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$". Make sure you fix this as Composer 2.0 will error.
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.

Reading composer.json of netresearch/contexts (analysis-8mojgD)
Found cached composer.json of netresearch/contexts (dev-analysis-8mojgD)
Reading composer.json of netresearch/contexts (analysis-z93OP6)
Found cached composer.json of netresearch/contexts (dev-analysis-z93OP6)
Reading composer.json of netresearch/contexts (0.5.x)
Skipped 0.5.x-dev, no composer file (cached from ref 3fed9b7e135ccb7b2485fcc6cea8b0148bb6587e)

**Comment by magicsunday** [comment]
Should be fixed with new release.
