### ISSUE TITLE
Selecting a context in a page returns an error on saving 

### ISSUE THREAD

**Issue by Clanver** [netresearch/t3x-contexts#27]
Hi! Thanks for the TYPO3 11 Update first! I got some problems though. For me it only works with content elements, but not pages.

When selecting a context on a page, i get the following error:

_Typed property Netresearch\Contexts\Service\DataHandlerService::$currentSettings must not be accessed before initialization_

```php
public/typo3conf/ext/contexts/Classes/Service/DataHandlerService.php line 98
        string $id,
        array $fieldArray,
        DataHandler $reference
    ): void {
        if (count($this->currentSettings) > 0) {
            if (!is_numeric($id)) {
                $id = $reference->substNEWwithIDs[$id];
            }
```

To reproduce the problem:
1. Create any kind of context
2. Go to page settings on any page in the pagetree
3. In the access tab, select your created context in any config
4. Look at the error

**Environment**
 - TYPO3 version: 11.5.25
 - PHP version: 7.4
 - Extension version: v3.0.0

**Comment by Clanver** [comment]
The "processDatamap_preProcessFieldArray" Hook is properly setting the $currentSettings array before the Hook "processDatamap_afterDatabaseOperations" is called. But an error is still generated.

My only simple "solution" is to remove the type declaration:
```PHP
  protected array $currentSettings = [];
````
to
```PHP
 protected $currentSettings = [];
```
 $currentSettings

**Comment by magicsunday** [comment]
Hi, I'm sorry it took so long, but I couldn't reproduce your problem in my test.

As I understand it, the error only occurs if no default value is defined for a property. But this is the case here.

However, I noticed that there were still a few places that were apparently not compatible with TYPO3 v11. I've now made a few adjustments. Can you please test again with the current status from the master branch to see whether this solves your problem?

**Comment by magicsunday** [comment]
As is often the case when testing, I now got the error. I have no idea why this occurs. I put another query around it. Please check with the master version.
