### ISSUE TITLE
Not using the forwarded IP, when using reverse proxy

### ISSUE THREAD

**Issue by Clanver** [netresearch/t3x-contexts#31]
**Bug description**
If the website uses a reverse proxy, all traffic will have the same ip adress. So the ip context will all be true or false depending on the ip.
since   $_SERVER['REMOTE_ADDR'] will contain the proxy adress.

Can we maybe include  $_SERVER['HTTP_X_FORWARDED_FOR']  as well? Which contains  the original ip adresses.

So for the file: https://github.com/netresearch/t3x-contexts/blob/master/Classes/Context/Type/IpContext.php

Something like:

```php
public function match(array $arDependencies = array())
    {
        $strCurIp = $this->get_client_ip();
      //  . . .
     }
```

```php
private function get_client_ip() {
        if (array_key_exists("HTTP_X_FORWARDED_FOR", $_SERVER)) {
            return  $_SERVER["HTTP_X_FORWARDED_FOR"];
        } else if (array_key_exists("REMOTE_ADDR", $_SERVER)) {
            return $_SERVER['REMOTE_ADDR'];
        } else if (array_key_exists("HTTP_CLIENT_IP", $_SERVER)) {
            return $_SERVER["HTTP_CLIENT_IP"];
        }

        return "";
    }
```

 
Or tie it to, if the TYPO3 Variable [SYS][reverseProxyIP] is set.

**Environment**
 - TYPO3 version: all
 - PHP version:  all
 - Extension version:  all

**Comment by CybotTM** [comment]
Please double check your reverse proxy setup.

This is already implemented with d5f5400
